package trabajopractico2;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class GUICodigoSecreto extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUICodigoSecreto.class.getName());
    private LogicaCodigoSecreto logica = new LogicaCodigoSecreto();

    /**
     * Creates new form GUICodigoSecreto
     */
    public GUICodigoSecreto() {
        initComponents();

        logica.generarCodigo();

        digito1.setText(String.valueOf(logica.obtenerUnDigito(0)));
        digito2.setText(String.valueOf(logica.obtenerUnDigito(1)));
        digito3.setText(String.valueOf(logica.obtenerUnDigito(2)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        digito1 = new javax.swing.JPasswordField();
        digito3 = new javax.swing.JPasswordField();
        digito2 = new javax.swing.JPasswordField();
        botonRevelar = new javax.swing.JButton();
        PistaMayorOMenor = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        txtIntento = new javax.swing.JTextField();
        Trofeo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Codigo Secreto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 103, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(240, 103, 0));

        digito1.setEditable(false);
        digito1.setBackground(new java.awt.Color(204, 204, 204));
        digito1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        digito1.setForeground(new java.awt.Color(153, 153, 153));
        digito1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digito1.setToolTipText("");
        digito1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        digito1.setEchoChar('$');
        digito1.setName(""); // NOI18N
        digito1.addActionListener(this::digito1ActionPerformed);

        digito3.setEditable(false);
        digito3.setBackground(new java.awt.Color(204, 204, 204));
        digito3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        digito3.setForeground(new java.awt.Color(153, 153, 153));
        digito3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digito3.setToolTipText("");
        digito3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        digito3.setEchoChar('$');
        digito3.addActionListener(this::digito3ActionPerformed);

        digito2.setEditable(false);
        digito2.setBackground(new java.awt.Color(204, 204, 204));
        digito2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        digito2.setForeground(new java.awt.Color(153, 153, 153));
        digito2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digito2.setToolTipText("");
        digito2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        digito2.setEchoChar('$');
        digito2.addActionListener(this::digito2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {digito1, digito2, digito3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {digito1, digito2, digito3});

        botonRevelar.setBackground(new java.awt.Color(240, 103, 0));
        botonRevelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        botonRevelar.setText(" Revelar Numero");
        botonRevelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        botonRevelar.addActionListener(this::botonRevelarActionPerformed);

        PistaMayorOMenor.setBackground(new java.awt.Color(40, 72, 112));
        PistaMayorOMenor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PistaMayorOMenor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PistaMayorOMenor.setText("Necesitas una pista?");

        titulo.setBackground(new java.awt.Color(240, 103, 0));
        titulo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 42)); // NOI18N
        titulo.setForeground(new java.awt.Color(240, 103, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("El Codigo Secreto");

        txtIntento.setBackground(new java.awt.Color(240, 103, 0));
        txtIntento.setColumns(1);
        txtIntento.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtIntento.setForeground(new java.awt.Color(255, 255, 255));
        txtIntento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIntento.setToolTipText("");
        txtIntento.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createTitledBorder(null, "Escribe 3 digitos + ENTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)))); // NOI18N
        txtIntento.setName(""); // NOI18N
        txtIntento.addActionListener(this::txtIntentoActionPerformed);
        txtIntento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIntentoKeyPressed(evt);
            }
        });

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonRevelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PistaMayorOMenor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtIntento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Trofeo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PistaMayorOMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Trofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PistaMayorOMenor)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(botonRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Trofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void digito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digito1ActionPerformed

    private void botonRevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevelarActionPerformed
        int posicion = logica.puedeUsarAyuda();

        if (posicion == 0) {
            digito1.setEchoChar((char) 0);
            PistaMayorOMenor.setText("Se reveló el Primer Numero.");
        } else if (posicion == 1) {
            digito2.setEchoChar((char) 0);
            PistaMayorOMenor.setText("Se reveló el Segundo Numero.");
        } else {
            JOptionPane.showMessageDialog(this, "No hay mas Revelaciones!");
        }
    }//GEN-LAST:event_botonRevelarActionPerformed

    private void digito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digito2ActionPerformed

    private void txtIntentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntentoKeyPressed

    private void digito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digito3ActionPerformed

    private void txtIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntentoActionPerformed
        // TODO add your handling code here:
        String textUser = txtIntento.getText();
        if (textUser.length() == 3) {
            logica.sumarContador();
            int numUser = Integer.parseInt(textUser);
            char digitoUser1 = textUser.charAt(0);
            char digitoUser2 = textUser.charAt(1);
            char digitoUser3 = textUser.charAt(2);

            if (logica.comparacion(digitoUser1, digitoUser2, digitoUser3)) {
                digito1.setEchoChar((char) 0);
                digito2.setEchoChar((char) 0);
                digito3.setEchoChar((char) 0);
                try {
                    URL url = new java.net.URL("https://images.vexels.com/media/users/3/202189/isolated/lists/4f3a5cb84297726d74d69dce22676f83-trofeo-numero-1-plano.png");
                    ImageIcon icon = new javax.swing.ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);

                    Trofeo.setText("");
                    Trofeo.setIcon(new javax.swing.ImageIcon(img));
                    Trofeo.setVisible(true);
                } catch (Exception e) {
                    System.out.println("Error al cargar la imagen: " + e.getMessage());
                }
                String mensaje = " ¡Ganaste!\n"
                        + "Código correcto: " + logica.getCodigoSecreto() + "\n"
                        + "Intentos totales: " + logica.getContadorIntentos();
                String titulo = "Victoria";
                JOptionPane.showMessageDialog(this, mensaje, titulo, WIDTH);
            } else if (numUser > logica.getCodigoSecreto()) {
                PistaMayorOMenor.setText("El numero secreto es menor.");
            } else {
                PistaMayorOMenor.setText("El numero secreto es mayor.");
            }
        } else {
            PistaMayorOMenor.setText("Escribe 3 digitos porfavor");
        }
    }//GEN-LAST:event_txtIntentoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUICodigoSecreto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PistaMayorOMenor;
    private javax.swing.JLabel Trofeo;
    private javax.swing.JButton botonRevelar;
    private javax.swing.JPasswordField digito1;
    private javax.swing.JPasswordField digito2;
    private javax.swing.JPasswordField digito3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtIntento;
    // End of variables declaration//GEN-END:variables
}
